version: "3.3"

networks:
  app_network:
    driver: bridge

services:
  localstack:
    container_name: s3
    image: localstack/localstack:latest
    restart: always
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-2
      - USE_SSL=false
      - DEBUG=1
    networks:
      - app_network

  lac-backend:
    container_name: lac-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - localstack
    networks:
      - app_network