version: "3.3"

services:
  localstack:
    image: localstack/localstack:latest
    restart: always
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-2
      - USE_SSL=false
      - DEBUG=1