version: "3.3"

services:
  localstack:
    container_name: s3
    image: localstack/localstack:latest
    restart: on-failure
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-2
      - USE_SSL=false
      - DEBUG=1

  postgres:
    container_name: postgres
    image: postgres:9.6.20-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=passw@rd
      - POSTGRES_USER=loc@l
      - POSTGRES_DB=test